//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("MyLifeModel", "tblRoles_Users", "tblRoles", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MyLife.DataAccess.tblRoles), "tblUsers", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MyLife.DataAccess.tblUsers))]

// Original file name:
// Generation date: 4/16/2009 1:59:50 PM
namespace MyLife.DataAccess
{
    
    /// <summary>
    /// There are no comments for MyLifeEntities in the schema.
    /// </summary>
    public partial class MyLifeEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new MyLifeEntities object using the connection string found in the 'MyLifeEntities' section of the application configuration file.
        /// </summary>
        public MyLifeEntities() : 
                base("name=MyLifeEntities", "MyLifeEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MyLifeEntities object.
        /// </summary>
        public MyLifeEntities(string connectionString) : 
                base(connectionString, "MyLifeEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MyLifeEntities object.
        /// </summary>
        public MyLifeEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "MyLifeEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for tblLinks in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<tblLinks> tblLinks
        {
            get
            {
                if ((this._tblLinks == null))
                {
                    this._tblLinks = base.CreateQuery<tblLinks>("[tblLinks]");
                }
                return this._tblLinks;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tblLinks> _tblLinks;
        /// <summary>
        /// There are no comments for tblProfiles in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<tblProfiles> tblProfiles
        {
            get
            {
                if ((this._tblProfiles == null))
                {
                    this._tblProfiles = base.CreateQuery<tblProfiles>("[tblProfiles]");
                }
                return this._tblProfiles;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tblProfiles> _tblProfiles;
        /// <summary>
        /// There are no comments for tblRoles in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<tblRoles> tblRoles
        {
            get
            {
                if ((this._tblRoles == null))
                {
                    this._tblRoles = base.CreateQuery<tblRoles>("[tblRoles]");
                }
                return this._tblRoles;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tblRoles> _tblRoles;
        /// <summary>
        /// There are no comments for tblUsers in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<tblUsers> tblUsers
        {
            get
            {
                if ((this._tblUsers == null))
                {
                    this._tblUsers = base.CreateQuery<tblUsers>("[tblUsers]");
                }
                return this._tblUsers;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tblUsers> _tblUsers;
        /// <summary>
        /// There are no comments for tblNews in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<tblNews> tblNews
        {
            get
            {
                if ((this._tblNews == null))
                {
                    this._tblNews = base.CreateQuery<tblNews>("[tblNews]");
                }
                return this._tblNews;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tblNews> _tblNews;
        /// <summary>
        /// There are no comments for tblLinks in the schema.
        /// </summary>
        public void AddTotblLinks(tblLinks tblLinks)
        {
            base.AddObject("tblLinks", tblLinks);
        }
        /// <summary>
        /// There are no comments for tblProfiles in the schema.
        /// </summary>
        public void AddTotblProfiles(tblProfiles tblProfiles)
        {
            base.AddObject("tblProfiles", tblProfiles);
        }
        /// <summary>
        /// There are no comments for tblRoles in the schema.
        /// </summary>
        public void AddTotblRoles(tblRoles tblRoles)
        {
            base.AddObject("tblRoles", tblRoles);
        }
        /// <summary>
        /// There are no comments for tblUsers in the schema.
        /// </summary>
        public void AddTotblUsers(tblUsers tblUsers)
        {
            base.AddObject("tblUsers", tblUsers);
        }
        /// <summary>
        /// There are no comments for tblNews in the schema.
        /// </summary>
        public void AddTotblNews(tblNews tblNews)
        {
            base.AddObject("tblNews", tblNews);
        }
    }
    /// <summary>
    /// There are no comments for MyLifeModel.tblLinks in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MyLifeModel", Name="tblLinks")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class tblLinks : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tblLinks object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        /// <param name="modifiedBy">Initial value of ModifiedBy.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="url">Initial value of Url.</param>
        public static tblLinks CreatetblLinks(int id, global::System.DateTime createdDate, string createdBy, global::System.DateTime modifiedDate, string modifiedBy, string title, string url)
        {
            tblLinks tblLinks = new tblLinks();
            tblLinks.Id = id;
            tblLinks.CreatedDate = createdDate;
            tblLinks.CreatedBy = createdBy;
            tblLinks.ModifiedDate = modifiedDate;
            tblLinks.ModifiedBy = modifiedBy;
            tblLinks.Title = title;
            tblLinks.Url = url;
            return tblLinks;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this.ReportPropertyChanging("CreatedDate");
                this._CreatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatedDate");
                this.OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this.ReportPropertyChanging("CreatedBy");
                this._CreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CreatedBy");
                this.OnCreatedByChanged();
            }
        }
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this.ReportPropertyChanging("ModifiedBy");
                this._ModifiedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ModifiedBy");
                this.OnModifiedByChanged();
            }
        }
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Url in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this._Url;
            }
            set
            {
                this.OnUrlChanging(value);
                this.ReportPropertyChanging("Url");
                this._Url = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Url");
                this.OnUrlChanged();
            }
        }
        private string _Url;
        partial void OnUrlChanging(string value);
        partial void OnUrlChanged();
    }
    /// <summary>
    /// There are no comments for MyLifeModel.tblProfiles in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MyLifeModel", Name="tblProfiles")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class tblProfiles : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tblProfiles object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="userName">Initial value of UserName.</param>
        /// <param name="propertyNames">Initial value of PropertyNames.</param>
        /// <param name="propertyValues">Initial value of PropertyValues.</param>
        /// <param name="lastUpdatedDate">Initial value of LastUpdatedDate.</param>
        public static tblProfiles CreatetblProfiles(int id, string userName, string propertyNames, string propertyValues, global::System.DateTime lastUpdatedDate)
        {
            tblProfiles tblProfiles = new tblProfiles();
            tblProfiles.Id = id;
            tblProfiles.UserName = userName;
            tblProfiles.PropertyNames = propertyNames;
            tblProfiles.PropertyValues = propertyValues;
            tblProfiles.LastUpdatedDate = lastUpdatedDate;
            return tblProfiles;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this.ReportPropertyChanging("UserName");
                this._UserName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("UserName");
                this.OnUserNameChanged();
            }
        }
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property PropertyNames in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyNames
        {
            get
            {
                return this._PropertyNames;
            }
            set
            {
                this.OnPropertyNamesChanging(value);
                this.ReportPropertyChanging("PropertyNames");
                this._PropertyNames = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PropertyNames");
                this.OnPropertyNamesChanged();
            }
        }
        private string _PropertyNames;
        partial void OnPropertyNamesChanging(string value);
        partial void OnPropertyNamesChanged();
        /// <summary>
        /// There are no comments for Property PropertyValues in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyValues
        {
            get
            {
                return this._PropertyValues;
            }
            set
            {
                this.OnPropertyValuesChanging(value);
                this.ReportPropertyChanging("PropertyValues");
                this._PropertyValues = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PropertyValues");
                this.OnPropertyValuesChanged();
            }
        }
        private string _PropertyValues;
        partial void OnPropertyValuesChanging(string value);
        partial void OnPropertyValuesChanged();
        /// <summary>
        /// There are no comments for Property LastUpdatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime LastUpdatedDate
        {
            get
            {
                return this._LastUpdatedDate;
            }
            set
            {
                this.OnLastUpdatedDateChanging(value);
                this.ReportPropertyChanging("LastUpdatedDate");
                this._LastUpdatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastUpdatedDate");
                this.OnLastUpdatedDateChanged();
            }
        }
        private global::System.DateTime _LastUpdatedDate;
        partial void OnLastUpdatedDateChanging(global::System.DateTime value);
        partial void OnLastUpdatedDateChanged();
    }
    /// <summary>
    /// There are no comments for MyLifeModel.tblRoles in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MyLifeModel", Name="tblRoles")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class tblRoles : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tblRoles object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        public static tblRoles CreatetblRoles(int id, string name)
        {
            tblRoles tblRoles = new tblRoles();
            tblRoles.Id = id;
            tblRoles.Name = name;
            return tblRoles;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MyLifeModel", "tblRoles_Users", "tblUsers")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<tblUsers> Users
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<tblUsers>("MyLifeModel.tblRoles_Users", "tblUsers");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<tblUsers>("MyLifeModel.tblRoles_Users", "tblUsers", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for MyLifeModel.tblUsers in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MyLifeModel", Name="tblUsers")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class tblUsers : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tblUsers object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="userName">Initial value of UserName.</param>
        /// <param name="password">Initial value of Password.</param>
        /// <param name="passwordFormat">Initial value of PasswordFormat.</param>
        /// <param name="passwordSalt">Initial value of PasswordSalt.</param>
        /// <param name="email">Initial value of Email.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="isApproved">Initial value of IsApproved.</param>
        /// <param name="isLockedOut">Initial value of IsLockedOut.</param>
        /// <param name="lastLoginDate">Initial value of LastLoginDate.</param>
        /// <param name="lastPasswordChangedDate">Initial value of LastPasswordChangedDate.</param>
        /// <param name="lastLockoutDate">Initial value of LastLockoutDate.</param>
        public static tblUsers CreatetblUsers(int id, string userName, string password, int passwordFormat, string passwordSalt, string email, global::System.DateTime createdDate, bool isApproved, bool isLockedOut, global::System.DateTime lastLoginDate, global::System.DateTime lastPasswordChangedDate, global::System.DateTime lastLockoutDate)
        {
            tblUsers tblUsers = new tblUsers();
            tblUsers.Id = id;
            tblUsers.UserName = userName;
            tblUsers.Password = password;
            tblUsers.PasswordFormat = passwordFormat;
            tblUsers.PasswordSalt = passwordSalt;
            tblUsers.Email = email;
            tblUsers.CreatedDate = createdDate;
            tblUsers.IsApproved = isApproved;
            tblUsers.IsLockedOut = isLockedOut;
            tblUsers.LastLoginDate = lastLoginDate;
            tblUsers.LastPasswordChangedDate = lastPasswordChangedDate;
            tblUsers.LastLockoutDate = lastLockoutDate;
            return tblUsers;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this.ReportPropertyChanging("UserName");
                this._UserName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("UserName");
                this.OnUserNameChanged();
            }
        }
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this.ReportPropertyChanging("Password");
                this._Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Password");
                this.OnPasswordChanged();
            }
        }
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property PasswordFormat in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int PasswordFormat
        {
            get
            {
                return this._PasswordFormat;
            }
            set
            {
                this.OnPasswordFormatChanging(value);
                this.ReportPropertyChanging("PasswordFormat");
                this._PasswordFormat = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PasswordFormat");
                this.OnPasswordFormatChanged();
            }
        }
        private int _PasswordFormat;
        partial void OnPasswordFormatChanging(int value);
        partial void OnPasswordFormatChanged();
        /// <summary>
        /// There are no comments for Property PasswordSalt in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordSalt
        {
            get
            {
                return this._PasswordSalt;
            }
            set
            {
                this.OnPasswordSaltChanging(value);
                this.ReportPropertyChanging("PasswordSalt");
                this._PasswordSalt = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PasswordSalt");
                this.OnPasswordSaltChanged();
            }
        }
        private string _PasswordSalt;
        partial void OnPasswordSaltChanging(string value);
        partial void OnPasswordSaltChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this.ReportPropertyChanging("Email");
                this._Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Email");
                this.OnEmailChanged();
            }
        }
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this.ReportPropertyChanging("CreatedDate");
                this._CreatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatedDate");
                this.OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property IsApproved in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsApproved
        {
            get
            {
                return this._IsApproved;
            }
            set
            {
                this.OnIsApprovedChanging(value);
                this.ReportPropertyChanging("IsApproved");
                this._IsApproved = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsApproved");
                this.OnIsApprovedChanged();
            }
        }
        private bool _IsApproved;
        partial void OnIsApprovedChanging(bool value);
        partial void OnIsApprovedChanged();
        /// <summary>
        /// There are no comments for Property IsLockedOut in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLockedOut
        {
            get
            {
                return this._IsLockedOut;
            }
            set
            {
                this.OnIsLockedOutChanging(value);
                this.ReportPropertyChanging("IsLockedOut");
                this._IsLockedOut = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsLockedOut");
                this.OnIsLockedOutChanged();
            }
        }
        private bool _IsLockedOut;
        partial void OnIsLockedOutChanging(bool value);
        partial void OnIsLockedOutChanged();
        /// <summary>
        /// There are no comments for Property LastLoginDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime LastLoginDate
        {
            get
            {
                return this._LastLoginDate;
            }
            set
            {
                this.OnLastLoginDateChanging(value);
                this.ReportPropertyChanging("LastLoginDate");
                this._LastLoginDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastLoginDate");
                this.OnLastLoginDateChanged();
            }
        }
        private global::System.DateTime _LastLoginDate;
        partial void OnLastLoginDateChanging(global::System.DateTime value);
        partial void OnLastLoginDateChanged();
        /// <summary>
        /// There are no comments for Property LastPasswordChangedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime LastPasswordChangedDate
        {
            get
            {
                return this._LastPasswordChangedDate;
            }
            set
            {
                this.OnLastPasswordChangedDateChanging(value);
                this.ReportPropertyChanging("LastPasswordChangedDate");
                this._LastPasswordChangedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastPasswordChangedDate");
                this.OnLastPasswordChangedDateChanged();
            }
        }
        private global::System.DateTime _LastPasswordChangedDate;
        partial void OnLastPasswordChangedDateChanging(global::System.DateTime value);
        partial void OnLastPasswordChangedDateChanged();
        /// <summary>
        /// There are no comments for Property LastLockoutDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime LastLockoutDate
        {
            get
            {
                return this._LastLockoutDate;
            }
            set
            {
                this.OnLastLockoutDateChanging(value);
                this.ReportPropertyChanging("LastLockoutDate");
                this._LastLockoutDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastLockoutDate");
                this.OnLastLockoutDateChanged();
            }
        }
        private global::System.DateTime _LastLockoutDate;
        partial void OnLastLockoutDateChanging(global::System.DateTime value);
        partial void OnLastLockoutDateChanged();
        /// <summary>
        /// There are no comments for Roles in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MyLifeModel", "tblRoles_Users", "tblRoles")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<tblRoles> Roles
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<tblRoles>("MyLifeModel.tblRoles_Users", "tblRoles");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<tblRoles>("MyLifeModel.tblRoles_Users", "tblRoles", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for MyLifeModel.tblNews in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MyLifeModel", Name="tblNews")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class tblNews : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tblNews object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        /// <param name="modifiedBy">Initial value of ModifiedBy.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="slug">Initial value of Slug.</param>
        /// <param name="content">Initial value of Content.</param>
        public static tblNews CreatetblNews(int id, global::System.DateTime createdDate, string createdBy, global::System.DateTime modifiedDate, string modifiedBy, string title, string slug, string content)
        {
            tblNews tblNews = new tblNews();
            tblNews.Id = id;
            tblNews.CreatedDate = createdDate;
            tblNews.CreatedBy = createdBy;
            tblNews.ModifiedDate = modifiedDate;
            tblNews.ModifiedBy = modifiedBy;
            tblNews.Title = title;
            tblNews.Slug = slug;
            tblNews.Content = content;
            return tblNews;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this.ReportPropertyChanging("CreatedDate");
                this._CreatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatedDate");
                this.OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this.ReportPropertyChanging("CreatedBy");
                this._CreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CreatedBy");
                this.OnCreatedByChanged();
            }
        }
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this.ReportPropertyChanging("ModifiedBy");
                this._ModifiedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ModifiedBy");
                this.OnModifiedByChanged();
            }
        }
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Slug in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Slug
        {
            get
            {
                return this._Slug;
            }
            set
            {
                this.OnSlugChanging(value);
                this.ReportPropertyChanging("Slug");
                this._Slug = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Slug");
                this.OnSlugChanged();
            }
        }
        private string _Slug;
        partial void OnSlugChanging(string value);
        partial void OnSlugChanged();
        /// <summary>
        /// There are no comments for Property Content in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                this.OnContentChanging(value);
                this.ReportPropertyChanging("Content");
                this._Content = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Content");
                this.OnContentChanged();
            }
        }
        private string _Content;
        partial void OnContentChanging(string value);
        partial void OnContentChanged();
    }
}
