//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLife.Web.Blogs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyLife.Web.Blogs.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phản hồi của bạn đã được ghi nhận.
        /// </summary>
        public static string AddCommentSuccess {
            get {
                return ResourceManager.GetString("AddCommentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm bài viết mới.
        /// </summary>
        public static string AddPost {
            get {
                return ResourceManager.GetString("AddPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý blog.
        /// </summary>
        public static string BlogManage {
            get {
                return ResourceManager.GetString("BlogManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog {0} không có trong hệ thống.
        /// </summary>
        public static string BlogNotExist {
            get {
                return ResourceManager.GetString("BlogNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url của bạn không hợp lệ..
        /// </summary>
        public static string BlogrollLinkNotValidate {
            get {
                return ResourceManager.GetString("BlogrollLinkNotValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogrolls.
        /// </summary>
        public static string Blogrolls {
            get {
                return ResourceManager.GetString("Blogrolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các chủ đề.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryExist.
        /// </summary>
        public static string CategoryExist {
            get {
                return ResourceManager.GetString("CategoryExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ đề này không tồn tại hoặc đã bị xóa.
        /// </summary>
        public static string CategoryNotExist {
            get {
                return ResourceManager.GetString("CategoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các phản hồi.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phản hồi nặc danh đã bị khóa.
        /// </summary>
        public static string CommentsAnonymousLock {
            get {
                return ResourceManager.GetString("CommentsAnonymousLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phản hồi đã bị khóa.
        /// </summary>
        public static string CommentsLock {
            get {
                return ResourceManager.GetString("CommentsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xóa bài viết này?.
        /// </summary>
        public static string ConfirmDeletePost {
            get {
                return ResourceManager.GetString("ConfirmDeletePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết này với tiêu đề này đã có trong blog của bạn.
        /// </summary>
        public static string DuplicatePost {
            get {
                return ResourceManager.GetString("DuplicatePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa bài viết.
        /// </summary>
        public static string EditPost {
            get {
                return ResourceManager.GetString("EditPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các bài viết hot.
        /// </summary>
        public static string HotPostsOfBlog {
            get {
                return ResourceManager.GetString("HotPostsOfBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import rss feed.
        /// </summary>
        public static string ImportRss {
            get {
                return ResourceManager.GetString("ImportRss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết {0} không tồn tại.
        /// </summary>
        public static string PostNotExist {
            get {
                return ResourceManager.GetString("PostNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các phản hồi gần đây.
        /// </summary>
        public static string RecentComments {
            get {
                return ResourceManager.GetString("RecentComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các bài viết mới.
        /// </summary>
        public static string RecentPosts {
            get {
                return ResourceManager.GetString("RecentPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rss url không tồn tại.
        /// </summary>
        public static string RssUrlNotFound {
            get {
                return ResourceManager.GetString("RssUrlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết của bạn đã được lưu lại.
        /// </summary>
        public static string SavePostSuccess {
            get {
                return ResourceManager.GetString("SavePostSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticky Posts.
        /// </summary>
        public static string StickyPosts {
            get {
                return ResourceManager.GetString("StickyPosts", resourceCulture);
            }
        }
    }
}
