//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("MyLifeModel", "tblFriends_FriendsInGroups", "tblFriends_Friends", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MyLife.DataAccess.Friends.tblFriends_Friends), "tblFriends_Groups", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MyLife.DataAccess.Friends.tblFriends_Groups))]

// Original file name:
// Generation date: 4/16/2009 1:59:50 PM
namespace MyLife.DataAccess.Friends
{
    
    /// <summary>
    /// There are no comments for FriendsEntities in the schema.
    /// </summary>
    public partial class FriendsEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new FriendsEntities object using the connection string found in the 'FriendsEntities' section of the application configuration file.
        /// </summary>
        public FriendsEntities() : 
                base("name=FriendsEntities", "FriendsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new FriendsEntities object.
        /// </summary>
        public FriendsEntities(string connectionString) : 
                base(connectionString, "FriendsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new FriendsEntities object.
        /// </summary>
        public FriendsEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "FriendsEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for tblFriends_Friends in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<tblFriends_Friends> tblFriends_Friends
        {
            get
            {
                if ((this._tblFriends_Friends == null))
                {
                    this._tblFriends_Friends = base.CreateQuery<tblFriends_Friends>("[tblFriends_Friends]");
                }
                return this._tblFriends_Friends;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tblFriends_Friends> _tblFriends_Friends;
        /// <summary>
        /// There are no comments for tblFriends_Groups in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<tblFriends_Groups> tblFriends_Groups
        {
            get
            {
                if ((this._tblFriends_Groups == null))
                {
                    this._tblFriends_Groups = base.CreateQuery<tblFriends_Groups>("[tblFriends_Groups]");
                }
                return this._tblFriends_Groups;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tblFriends_Groups> _tblFriends_Groups;
        /// <summary>
        /// There are no comments for tblFriends_Friends in the schema.
        /// </summary>
        public void AddTotblFriends_Friends(tblFriends_Friends tblFriends_Friends)
        {
            base.AddObject("tblFriends_Friends", tblFriends_Friends);
        }
        /// <summary>
        /// There are no comments for tblFriends_Groups in the schema.
        /// </summary>
        public void AddTotblFriends_Groups(tblFriends_Groups tblFriends_Groups)
        {
            base.AddObject("tblFriends_Groups", tblFriends_Groups);
        }
    }
    /// <summary>
    /// There are no comments for MyLifeModel.tblFriends_Friends in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MyLifeModel", Name="tblFriends_Friends")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class tblFriends_Friends : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tblFriends_Friends object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        /// <param name="modifiedBy">Initial value of ModifiedBy.</param>
        /// <param name="fullName">Initial value of FullName.</param>
        /// <param name="letter">Initial value of Letter.</param>
        /// <param name="birthday">Initial value of Birthday.</param>
        /// <param name="gender">Initial value of Gender.</param>
        public static tblFriends_Friends CreatetblFriends_Friends(int id, global::System.DateTime createdDate, string createdBy, global::System.DateTime modifiedDate, string modifiedBy, string fullName, string letter, global::System.DateTime birthday, bool gender)
        {
            tblFriends_Friends tblFriends_Friends = new tblFriends_Friends();
            tblFriends_Friends.Id = id;
            tblFriends_Friends.CreatedDate = createdDate;
            tblFriends_Friends.CreatedBy = createdBy;
            tblFriends_Friends.ModifiedDate = modifiedDate;
            tblFriends_Friends.ModifiedBy = modifiedBy;
            tblFriends_Friends.FullName = fullName;
            tblFriends_Friends.Letter = letter;
            tblFriends_Friends.Birthday = birthday;
            tblFriends_Friends.Gender = gender;
            return tblFriends_Friends;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this.ReportPropertyChanging("CreatedDate");
                this._CreatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatedDate");
                this.OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this.ReportPropertyChanging("CreatedBy");
                this._CreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CreatedBy");
                this.OnCreatedByChanged();
            }
        }
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this.ReportPropertyChanging("ModifiedBy");
                this._ModifiedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ModifiedBy");
                this.OnModifiedByChanged();
            }
        }
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property FullName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this._FullName;
            }
            set
            {
                this.OnFullNameChanging(value);
                this.ReportPropertyChanging("FullName");
                this._FullName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FullName");
                this.OnFullNameChanged();
            }
        }
        private string _FullName;
        partial void OnFullNameChanging(string value);
        partial void OnFullNameChanged();
        /// <summary>
        /// There are no comments for Property Letter in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Letter
        {
            get
            {
                return this._Letter;
            }
            set
            {
                this.OnLetterChanging(value);
                this.ReportPropertyChanging("Letter");
                this._Letter = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Letter");
                this.OnLetterChanged();
            }
        }
        private string _Letter;
        partial void OnLetterChanging(string value);
        partial void OnLetterChanged();
        /// <summary>
        /// There are no comments for Property NickName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName
        {
            get
            {
                return this._NickName;
            }
            set
            {
                this.OnNickNameChanging(value);
                this.ReportPropertyChanging("NickName");
                this._NickName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NickName");
                this.OnNickNameChanged();
            }
        }
        private string _NickName;
        partial void OnNickNameChanging(string value);
        partial void OnNickNameChanged();
        /// <summary>
        /// There are no comments for Property Birthday in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Birthday
        {
            get
            {
                return this._Birthday;
            }
            set
            {
                this.OnBirthdayChanging(value);
                this.ReportPropertyChanging("Birthday");
                this._Birthday = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Birthday");
                this.OnBirthdayChanged();
            }
        }
        private global::System.DateTime _Birthday;
        partial void OnBirthdayChanging(global::System.DateTime value);
        partial void OnBirthdayChanged();
        /// <summary>
        /// There are no comments for Property Gender in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Gender
        {
            get
            {
                return this._Gender;
            }
            set
            {
                this.OnGenderChanging(value);
                this.ReportPropertyChanging("Gender");
                this._Gender = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Gender");
                this.OnGenderChanged();
            }
        }
        private bool _Gender;
        partial void OnGenderChanging(bool value);
        partial void OnGenderChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this.ReportPropertyChanging("Email");
                this._Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Email");
                this.OnEmailChanged();
            }
        }
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property AvatarUrl in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarUrl
        {
            get
            {
                return this._AvatarUrl;
            }
            set
            {
                this.OnAvatarUrlChanging(value);
                this.ReportPropertyChanging("AvatarUrl");
                this._AvatarUrl = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("AvatarUrl");
                this.OnAvatarUrlChanged();
            }
        }
        private string _AvatarUrl;
        partial void OnAvatarUrlChanging(string value);
        partial void OnAvatarUrlChanged();
        /// <summary>
        /// There are no comments for Property PhoneNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this._PhoneNumber;
            }
            set
            {
                this.OnPhoneNumberChanging(value);
                this.ReportPropertyChanging("PhoneNumber");
                this._PhoneNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PhoneNumber");
                this.OnPhoneNumberChanged();
            }
        }
        private string _PhoneNumber;
        partial void OnPhoneNumberChanging(string value);
        partial void OnPhoneNumberChanged();
        /// <summary>
        /// There are no comments for Property MobileNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this._MobileNumber;
            }
            set
            {
                this.OnMobileNumberChanging(value);
                this.ReportPropertyChanging("MobileNumber");
                this._MobileNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("MobileNumber");
                this.OnMobileNumberChanged();
            }
        }
        private string _MobileNumber;
        partial void OnMobileNumberChanging(string value);
        partial void OnMobileNumberChanged();
        /// <summary>
        /// There are no comments for Property YahooNick in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string YahooNick
        {
            get
            {
                return this._YahooNick;
            }
            set
            {
                this.OnYahooNickChanging(value);
                this.ReportPropertyChanging("YahooNick");
                this._YahooNick = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("YahooNick");
                this.OnYahooNickChanged();
            }
        }
        private string _YahooNick;
        partial void OnYahooNickChanging(string value);
        partial void OnYahooNickChanged();
        /// <summary>
        /// There are no comments for Property SkypeNick in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SkypeNick
        {
            get
            {
                return this._SkypeNick;
            }
            set
            {
                this.OnSkypeNickChanging(value);
                this.ReportPropertyChanging("SkypeNick");
                this._SkypeNick = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SkypeNick");
                this.OnSkypeNickChanged();
            }
        }
        private string _SkypeNick;
        partial void OnSkypeNickChanging(string value);
        partial void OnSkypeNickChanged();
        /// <summary>
        /// There are no comments for Property Website in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Website
        {
            get
            {
                return this._Website;
            }
            set
            {
                this.OnWebsiteChanging(value);
                this.ReportPropertyChanging("Website");
                this._Website = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Website");
                this.OnWebsiteChanged();
            }
        }
        private string _Website;
        partial void OnWebsiteChanging(string value);
        partial void OnWebsiteChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this.ReportPropertyChanging("Address");
                this._Address = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Address");
                this.OnAddressChanged();
            }
        }
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this.ReportPropertyChanging("City");
                this._City = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("City");
                this.OnCityChanged();
            }
        }
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this.ReportPropertyChanging("Notes");
                this._Notes = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Notes");
                this.OnNotesChanged();
            }
        }
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Groups in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MyLifeModel", "tblFriends_FriendsInGroups", "tblFriends_Groups")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<tblFriends_Groups> Groups
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<tblFriends_Groups>("MyLifeModel.tblFriends_FriendsInGroups", "tblFriends_Groups");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<tblFriends_Groups>("MyLifeModel.tblFriends_FriendsInGroups", "tblFriends_Groups", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for MyLifeModel.tblFriends_Groups in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MyLifeModel", Name="tblFriends_Groups")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class tblFriends_Groups : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tblFriends_Groups object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        /// <param name="modifiedBy">Initial value of ModifiedBy.</param>
        /// <param name="name">Initial value of Name.</param>
        public static tblFriends_Groups CreatetblFriends_Groups(int id, global::System.DateTime createdDate, string createdBy, global::System.DateTime modifiedDate, string modifiedBy, string name)
        {
            tblFriends_Groups tblFriends_Groups = new tblFriends_Groups();
            tblFriends_Groups.Id = id;
            tblFriends_Groups.CreatedDate = createdDate;
            tblFriends_Groups.CreatedBy = createdBy;
            tblFriends_Groups.ModifiedDate = modifiedDate;
            tblFriends_Groups.ModifiedBy = modifiedBy;
            tblFriends_Groups.Name = name;
            return tblFriends_Groups;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this.ReportPropertyChanging("CreatedDate");
                this._CreatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatedDate");
                this.OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this.ReportPropertyChanging("CreatedBy");
                this._CreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CreatedBy");
                this.OnCreatedByChanged();
            }
        }
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this.ReportPropertyChanging("ModifiedBy");
                this._ModifiedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ModifiedBy");
                this.OnModifiedByChanged();
            }
        }
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Friends in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MyLifeModel", "tblFriends_FriendsInGroups", "tblFriends_Friends")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<tblFriends_Friends> Friends
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<tblFriends_Friends>("MyLifeModel.tblFriends_FriendsInGroups", "tblFriends_Friends");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<tblFriends_Friends>("MyLifeModel.tblFriends_FriendsInGroups", "tblFriends_Friends", value);
                }
            }
        }
    }
}
