//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("BlogsModel", "tblBlogs_CategoriestblBlogs_Posts", "tblBlogs_Categories", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MyLife.DataAccess.Blogs.tblBlogs_Categories), "tblBlogs_Posts", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MyLife.DataAccess.Blogs.tblBlogs_Posts))]

// Original file name:
// Generation date: 6/15/2009 4:27:04 PM
namespace MyLife.DataAccess.Blogs
{
    
    /// <summary>
    /// There are no comments for BlogsEntities in the schema.
    /// </summary>
    public partial class BlogsEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new BlogsEntities object using the connection string found in the 'BlogsEntities' section of the application configuration file.
        /// </summary>
        public BlogsEntities() : 
                base("name=BlogsEntities", "BlogsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new BlogsEntities object.
        /// </summary>
        public BlogsEntities(string connectionString) : 
                base(connectionString, "BlogsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new BlogsEntities object.
        /// </summary>
        public BlogsEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "BlogsEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for tblBlogs_Blogrolls in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<tblBlogs_Blogrolls> tblBlogs_Blogrolls
        {
            get
            {
                if ((this._tblBlogs_Blogrolls == null))
                {
                    this._tblBlogs_Blogrolls = base.CreateQuery<tblBlogs_Blogrolls>("[tblBlogs_Blogrolls]");
                }
                return this._tblBlogs_Blogrolls;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tblBlogs_Blogrolls> _tblBlogs_Blogrolls;
        /// <summary>
        /// There are no comments for tblBlogs_Blogs in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<tblBlogs_Blogs> tblBlogs_Blogs
        {
            get
            {
                if ((this._tblBlogs_Blogs == null))
                {
                    this._tblBlogs_Blogs = base.CreateQuery<tblBlogs_Blogs>("[tblBlogs_Blogs]");
                }
                return this._tblBlogs_Blogs;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tblBlogs_Blogs> _tblBlogs_Blogs;
        /// <summary>
        /// There are no comments for tblBlogs_Categories in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<tblBlogs_Categories> tblBlogs_Categories
        {
            get
            {
                if ((this._tblBlogs_Categories == null))
                {
                    this._tblBlogs_Categories = base.CreateQuery<tblBlogs_Categories>("[tblBlogs_Categories]");
                }
                return this._tblBlogs_Categories;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tblBlogs_Categories> _tblBlogs_Categories;
        /// <summary>
        /// There are no comments for tblBlogs_Comments in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<tblBlogs_Comments> tblBlogs_Comments
        {
            get
            {
                if ((this._tblBlogs_Comments == null))
                {
                    this._tblBlogs_Comments = base.CreateQuery<tblBlogs_Comments>("[tblBlogs_Comments]");
                }
                return this._tblBlogs_Comments;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tblBlogs_Comments> _tblBlogs_Comments;
        /// <summary>
        /// There are no comments for tblBlogs_Posts in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<tblBlogs_Posts> tblBlogs_Posts
        {
            get
            {
                if ((this._tblBlogs_Posts == null))
                {
                    this._tblBlogs_Posts = base.CreateQuery<tblBlogs_Posts>("[tblBlogs_Posts]");
                }
                return this._tblBlogs_Posts;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tblBlogs_Posts> _tblBlogs_Posts;
        /// <summary>
        /// There are no comments for tblBlogs_Friends in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<tblBlogs_Friends> tblBlogs_Friends
        {
            get
            {
                if ((this._tblBlogs_Friends == null))
                {
                    this._tblBlogs_Friends = base.CreateQuery<tblBlogs_Friends>("[tblBlogs_Friends]");
                }
                return this._tblBlogs_Friends;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tblBlogs_Friends> _tblBlogs_Friends;
        /// <summary>
        /// There are no comments for tblBlogs_Blogrolls in the schema.
        /// </summary>
        public void AddTotblBlogs_Blogrolls(tblBlogs_Blogrolls tblBlogs_Blogrolls)
        {
            base.AddObject("tblBlogs_Blogrolls", tblBlogs_Blogrolls);
        }
        /// <summary>
        /// There are no comments for tblBlogs_Blogs in the schema.
        /// </summary>
        public void AddTotblBlogs_Blogs(tblBlogs_Blogs tblBlogs_Blogs)
        {
            base.AddObject("tblBlogs_Blogs", tblBlogs_Blogs);
        }
        /// <summary>
        /// There are no comments for tblBlogs_Categories in the schema.
        /// </summary>
        public void AddTotblBlogs_Categories(tblBlogs_Categories tblBlogs_Categories)
        {
            base.AddObject("tblBlogs_Categories", tblBlogs_Categories);
        }
        /// <summary>
        /// There are no comments for tblBlogs_Comments in the schema.
        /// </summary>
        public void AddTotblBlogs_Comments(tblBlogs_Comments tblBlogs_Comments)
        {
            base.AddObject("tblBlogs_Comments", tblBlogs_Comments);
        }
        /// <summary>
        /// There are no comments for tblBlogs_Posts in the schema.
        /// </summary>
        public void AddTotblBlogs_Posts(tblBlogs_Posts tblBlogs_Posts)
        {
            base.AddObject("tblBlogs_Posts", tblBlogs_Posts);
        }
        /// <summary>
        /// There are no comments for tblBlogs_Friends in the schema.
        /// </summary>
        public void AddTotblBlogs_Friends(tblBlogs_Friends tblBlogs_Friends)
        {
            base.AddObject("tblBlogs_Friends", tblBlogs_Friends);
        }
    }
    /// <summary>
    /// There are no comments for BlogsModel.tblBlogs_Blogrolls in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="BlogsModel", Name="tblBlogs_Blogrolls")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class tblBlogs_Blogrolls : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tblBlogs_Blogrolls object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="link">Initial value of Link.</param>
        /// <param name="blogId">Initial value of BlogId.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        /// <param name="modifiedBy">Initial value of ModifiedBy.</param>
        public static tblBlogs_Blogrolls CreatetblBlogs_Blogrolls(int id, string name, string link, int blogId, global::System.DateTime createdDate, string createdBy, global::System.DateTime modifiedDate, string modifiedBy)
        {
            tblBlogs_Blogrolls tblBlogs_Blogrolls = new tblBlogs_Blogrolls();
            tblBlogs_Blogrolls.Id = id;
            tblBlogs_Blogrolls.Name = name;
            tblBlogs_Blogrolls.Link = link;
            tblBlogs_Blogrolls.BlogId = blogId;
            tblBlogs_Blogrolls.CreatedDate = createdDate;
            tblBlogs_Blogrolls.CreatedBy = createdBy;
            tblBlogs_Blogrolls.ModifiedDate = modifiedDate;
            tblBlogs_Blogrolls.ModifiedBy = modifiedBy;
            return tblBlogs_Blogrolls;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Link in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Link
        {
            get
            {
                return this._Link;
            }
            set
            {
                this.OnLinkChanging(value);
                this.ReportPropertyChanging("Link");
                this._Link = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Link");
                this.OnLinkChanged();
            }
        }
        private string _Link;
        partial void OnLinkChanging(string value);
        partial void OnLinkChanged();
        /// <summary>
        /// There are no comments for Property BlogId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int BlogId
        {
            get
            {
                return this._BlogId;
            }
            set
            {
                this.OnBlogIdChanging(value);
                this.ReportPropertyChanging("BlogId");
                this._BlogId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("BlogId");
                this.OnBlogIdChanged();
            }
        }
        private int _BlogId;
        partial void OnBlogIdChanging(int value);
        partial void OnBlogIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this.ReportPropertyChanging("CreatedDate");
                this._CreatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatedDate");
                this.OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this.ReportPropertyChanging("CreatedBy");
                this._CreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CreatedBy");
                this.OnCreatedByChanged();
            }
        }
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this.ReportPropertyChanging("ModifiedBy");
                this._ModifiedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ModifiedBy");
                this.OnModifiedByChanged();
            }
        }
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
    }
    /// <summary>
    /// There are no comments for BlogsModel.tblBlogs_Blogs in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="BlogsModel", Name="tblBlogs_Blogs")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class tblBlogs_Blogs : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tblBlogs_Blogs object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="anonymousCommentEnabled">Initial value of AnonymousCommentEnabled.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        /// <param name="modifiedBy">Initial value of ModifiedBy.</param>
        /// <param name="daysCommentEnabled">Initial value of DaysCommentEnabled.</param>
        /// <param name="description">Initial value of Description.</param>
        /// <param name="moderationCommentEnable">Initial value of ModerationCommentEnable.</param>
        /// <param name="commentsEnabled">Initial value of CommentsEnabled.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="numberOfRecentPosts">Initial value of NumberOfRecentPosts.</param>
        /// <param name="numberOfRecentComments">Initial value of NumberOfRecentComments.</param>
        /// <param name="postsPerFeed">Initial value of PostsPerFeed.</param>
        /// <param name="postsPerPage">Initial value of PostsPerPage.</param>
        /// <param name="theme">Initial value of Theme.</param>
        public static tblBlogs_Blogs CreatetblBlogs_Blogs(
                    int id, 
                    bool anonymousCommentEnabled, 
                    global::System.DateTime createdDate, 
                    string createdBy, 
                    global::System.DateTime modifiedDate, 
                    string modifiedBy, 
                    int daysCommentEnabled, 
                    string description, 
                    bool moderationCommentEnable, 
                    bool commentsEnabled, 
                    string name, 
                    int numberOfRecentPosts, 
                    int numberOfRecentComments, 
                    int postsPerFeed, 
                    int postsPerPage, 
                    string theme)
        {
            tblBlogs_Blogs tblBlogs_Blogs = new tblBlogs_Blogs();
            tblBlogs_Blogs.Id = id;
            tblBlogs_Blogs.AnonymousCommentEnabled = anonymousCommentEnabled;
            tblBlogs_Blogs.CreatedDate = createdDate;
            tblBlogs_Blogs.CreatedBy = createdBy;
            tblBlogs_Blogs.ModifiedDate = modifiedDate;
            tblBlogs_Blogs.ModifiedBy = modifiedBy;
            tblBlogs_Blogs.DaysCommentEnabled = daysCommentEnabled;
            tblBlogs_Blogs.Description = description;
            tblBlogs_Blogs.ModerationCommentEnable = moderationCommentEnable;
            tblBlogs_Blogs.CommentsEnabled = commentsEnabled;
            tblBlogs_Blogs.Name = name;
            tblBlogs_Blogs.NumberOfRecentPosts = numberOfRecentPosts;
            tblBlogs_Blogs.NumberOfRecentComments = numberOfRecentComments;
            tblBlogs_Blogs.PostsPerFeed = postsPerFeed;
            tblBlogs_Blogs.PostsPerPage = postsPerPage;
            tblBlogs_Blogs.Theme = theme;
            return tblBlogs_Blogs;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property AnonymousCommentEnabled in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool AnonymousCommentEnabled
        {
            get
            {
                return this._AnonymousCommentEnabled;
            }
            set
            {
                this.OnAnonymousCommentEnabledChanging(value);
                this.ReportPropertyChanging("AnonymousCommentEnabled");
                this._AnonymousCommentEnabled = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AnonymousCommentEnabled");
                this.OnAnonymousCommentEnabledChanged();
            }
        }
        private bool _AnonymousCommentEnabled;
        partial void OnAnonymousCommentEnabledChanging(bool value);
        partial void OnAnonymousCommentEnabledChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this.ReportPropertyChanging("CreatedDate");
                this._CreatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatedDate");
                this.OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this.ReportPropertyChanging("CreatedBy");
                this._CreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CreatedBy");
                this.OnCreatedByChanged();
            }
        }
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this.ReportPropertyChanging("ModifiedBy");
                this._ModifiedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ModifiedBy");
                this.OnModifiedByChanged();
            }
        }
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property DaysCommentEnabled in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int DaysCommentEnabled
        {
            get
            {
                return this._DaysCommentEnabled;
            }
            set
            {
                this.OnDaysCommentEnabledChanging(value);
                this.ReportPropertyChanging("DaysCommentEnabled");
                this._DaysCommentEnabled = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DaysCommentEnabled");
                this.OnDaysCommentEnabledChanged();
            }
        }
        private int _DaysCommentEnabled;
        partial void OnDaysCommentEnabledChanging(int value);
        partial void OnDaysCommentEnabledChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property ModerationCommentEnable in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool ModerationCommentEnable
        {
            get
            {
                return this._ModerationCommentEnable;
            }
            set
            {
                this.OnModerationCommentEnableChanging(value);
                this.ReportPropertyChanging("ModerationCommentEnable");
                this._ModerationCommentEnable = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModerationCommentEnable");
                this.OnModerationCommentEnableChanged();
            }
        }
        private bool _ModerationCommentEnable;
        partial void OnModerationCommentEnableChanging(bool value);
        partial void OnModerationCommentEnableChanged();
        /// <summary>
        /// There are no comments for Property CommentsEnabled in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool CommentsEnabled
        {
            get
            {
                return this._CommentsEnabled;
            }
            set
            {
                this.OnCommentsEnabledChanging(value);
                this.ReportPropertyChanging("CommentsEnabled");
                this._CommentsEnabled = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CommentsEnabled");
                this.OnCommentsEnabledChanged();
            }
        }
        private bool _CommentsEnabled;
        partial void OnCommentsEnabledChanging(bool value);
        partial void OnCommentsEnabledChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property NumberOfRecentPosts in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfRecentPosts
        {
            get
            {
                return this._NumberOfRecentPosts;
            }
            set
            {
                this.OnNumberOfRecentPostsChanging(value);
                this.ReportPropertyChanging("NumberOfRecentPosts");
                this._NumberOfRecentPosts = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NumberOfRecentPosts");
                this.OnNumberOfRecentPostsChanged();
            }
        }
        private int _NumberOfRecentPosts;
        partial void OnNumberOfRecentPostsChanging(int value);
        partial void OnNumberOfRecentPostsChanged();
        /// <summary>
        /// There are no comments for Property NumberOfRecentComments in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfRecentComments
        {
            get
            {
                return this._NumberOfRecentComments;
            }
            set
            {
                this.OnNumberOfRecentCommentsChanging(value);
                this.ReportPropertyChanging("NumberOfRecentComments");
                this._NumberOfRecentComments = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NumberOfRecentComments");
                this.OnNumberOfRecentCommentsChanged();
            }
        }
        private int _NumberOfRecentComments;
        partial void OnNumberOfRecentCommentsChanging(int value);
        partial void OnNumberOfRecentCommentsChanged();
        /// <summary>
        /// There are no comments for Property PostsPerFeed in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int PostsPerFeed
        {
            get
            {
                return this._PostsPerFeed;
            }
            set
            {
                this.OnPostsPerFeedChanging(value);
                this.ReportPropertyChanging("PostsPerFeed");
                this._PostsPerFeed = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PostsPerFeed");
                this.OnPostsPerFeedChanged();
            }
        }
        private int _PostsPerFeed;
        partial void OnPostsPerFeedChanging(int value);
        partial void OnPostsPerFeedChanged();
        /// <summary>
        /// There are no comments for Property PostsPerPage in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int PostsPerPage
        {
            get
            {
                return this._PostsPerPage;
            }
            set
            {
                this.OnPostsPerPageChanging(value);
                this.ReportPropertyChanging("PostsPerPage");
                this._PostsPerPage = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PostsPerPage");
                this.OnPostsPerPageChanged();
            }
        }
        private int _PostsPerPage;
        partial void OnPostsPerPageChanging(int value);
        partial void OnPostsPerPageChanged();
        /// <summary>
        /// There are no comments for Property Theme in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Theme
        {
            get
            {
                return this._Theme;
            }
            set
            {
                this.OnThemeChanging(value);
                this.ReportPropertyChanging("Theme");
                this._Theme = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Theme");
                this.OnThemeChanged();
            }
        }
        private string _Theme;
        partial void OnThemeChanging(string value);
        partial void OnThemeChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this.ReportPropertyChanging("Status");
                this._Status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Status");
                this.OnStatusChanged();
            }
        }
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property AboutMe in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AboutMe
        {
            get
            {
                return this._AboutMe;
            }
            set
            {
                this.OnAboutMeChanging(value);
                this.ReportPropertyChanging("AboutMe");
                this._AboutMe = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("AboutMe");
                this.OnAboutMeChanged();
            }
        }
        private string _AboutMe;
        partial void OnAboutMeChanging(string value);
        partial void OnAboutMeChanged();
    }
    /// <summary>
    /// There are no comments for BlogsModel.tblBlogs_Categories in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="BlogsModel", Name="tblBlogs_Categories")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class tblBlogs_Categories : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tblBlogs_Categories object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        /// <param name="modifiedBy">Initial value of ModifiedBy.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="slug">Initial value of Slug.</param>
        /// <param name="blogId">Initial value of BlogId.</param>
        public static tblBlogs_Categories CreatetblBlogs_Categories(int id, global::System.DateTime createdDate, string createdBy, global::System.DateTime modifiedDate, string modifiedBy, string name, string slug, int blogId)
        {
            tblBlogs_Categories tblBlogs_Categories = new tblBlogs_Categories();
            tblBlogs_Categories.Id = id;
            tblBlogs_Categories.CreatedDate = createdDate;
            tblBlogs_Categories.CreatedBy = createdBy;
            tblBlogs_Categories.ModifiedDate = modifiedDate;
            tblBlogs_Categories.ModifiedBy = modifiedBy;
            tblBlogs_Categories.Name = name;
            tblBlogs_Categories.Slug = slug;
            tblBlogs_Categories.BlogId = blogId;
            return tblBlogs_Categories;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this.ReportPropertyChanging("CreatedDate");
                this._CreatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatedDate");
                this.OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this.ReportPropertyChanging("CreatedBy");
                this._CreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CreatedBy");
                this.OnCreatedByChanged();
            }
        }
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this.ReportPropertyChanging("ModifiedBy");
                this._ModifiedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ModifiedBy");
                this.OnModifiedByChanged();
            }
        }
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Slug in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Slug
        {
            get
            {
                return this._Slug;
            }
            set
            {
                this.OnSlugChanging(value);
                this.ReportPropertyChanging("Slug");
                this._Slug = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Slug");
                this.OnSlugChanged();
            }
        }
        private string _Slug;
        partial void OnSlugChanging(string value);
        partial void OnSlugChanged();
        /// <summary>
        /// There are no comments for Property BlogId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int BlogId
        {
            get
            {
                return this._BlogId;
            }
            set
            {
                this.OnBlogIdChanging(value);
                this.ReportPropertyChanging("BlogId");
                this._BlogId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("BlogId");
                this.OnBlogIdChanged();
            }
        }
        private int _BlogId;
        partial void OnBlogIdChanging(int value);
        partial void OnBlogIdChanged();
        /// <summary>
        /// There are no comments for Posts in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("BlogsModel", "tblBlogs_CategoriestblBlogs_Posts", "tblBlogs_Posts")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<tblBlogs_Posts> Posts
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<tblBlogs_Posts>("BlogsModel.tblBlogs_CategoriestblBlogs_Posts", "tblBlogs_Posts");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<tblBlogs_Posts>("BlogsModel.tblBlogs_CategoriestblBlogs_Posts", "tblBlogs_Posts", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for BlogsModel.tblBlogs_Comments in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="BlogsModel", Name="tblBlogs_Comments")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class tblBlogs_Comments : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tblBlogs_Comments object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        /// <param name="modifiedBy">Initial value of ModifiedBy.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="content">Initial value of Content.</param>
        /// <param name="email">Initial value of Email.</param>
        /// <param name="iP">Initial value of IP.</param>
        /// <param name="isApproved">Initial value of IsApproved.</param>
        /// <param name="postId">Initial value of PostId.</param>
        /// <param name="blogId">Initial value of BlogId.</param>
        public static tblBlogs_Comments CreatetblBlogs_Comments(int id, global::System.DateTime createdDate, string createdBy, global::System.DateTime modifiedDate, string modifiedBy, string name, string content, string email, string iP, bool isApproved, int postId, int blogId)
        {
            tblBlogs_Comments tblBlogs_Comments = new tblBlogs_Comments();
            tblBlogs_Comments.Id = id;
            tblBlogs_Comments.CreatedDate = createdDate;
            tblBlogs_Comments.CreatedBy = createdBy;
            tblBlogs_Comments.ModifiedDate = modifiedDate;
            tblBlogs_Comments.ModifiedBy = modifiedBy;
            tblBlogs_Comments.Name = name;
            tblBlogs_Comments.Content = content;
            tblBlogs_Comments.Email = email;
            tblBlogs_Comments.IP = iP;
            tblBlogs_Comments.IsApproved = isApproved;
            tblBlogs_Comments.PostId = postId;
            tblBlogs_Comments.BlogId = blogId;
            return tblBlogs_Comments;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this.ReportPropertyChanging("CreatedDate");
                this._CreatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatedDate");
                this.OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this.ReportPropertyChanging("CreatedBy");
                this._CreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CreatedBy");
                this.OnCreatedByChanged();
            }
        }
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this.ReportPropertyChanging("ModifiedBy");
                this._ModifiedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ModifiedBy");
                this.OnModifiedByChanged();
            }
        }
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Content in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                this.OnContentChanging(value);
                this.ReportPropertyChanging("Content");
                this._Content = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Content");
                this.OnContentChanged();
            }
        }
        private string _Content;
        partial void OnContentChanging(string value);
        partial void OnContentChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this.ReportPropertyChanging("Email");
                this._Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Email");
                this.OnEmailChanged();
            }
        }
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property IP in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string IP
        {
            get
            {
                return this._IP;
            }
            set
            {
                this.OnIPChanging(value);
                this.ReportPropertyChanging("IP");
                this._IP = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("IP");
                this.OnIPChanged();
            }
        }
        private string _IP;
        partial void OnIPChanging(string value);
        partial void OnIPChanged();
        /// <summary>
        /// There are no comments for Property IsApproved in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsApproved
        {
            get
            {
                return this._IsApproved;
            }
            set
            {
                this.OnIsApprovedChanging(value);
                this.ReportPropertyChanging("IsApproved");
                this._IsApproved = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsApproved");
                this.OnIsApprovedChanged();
            }
        }
        private bool _IsApproved;
        partial void OnIsApprovedChanging(bool value);
        partial void OnIsApprovedChanged();
        /// <summary>
        /// There are no comments for Property PostId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int PostId
        {
            get
            {
                return this._PostId;
            }
            set
            {
                this.OnPostIdChanging(value);
                this.ReportPropertyChanging("PostId");
                this._PostId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PostId");
                this.OnPostIdChanged();
            }
        }
        private int _PostId;
        partial void OnPostIdChanging(int value);
        partial void OnPostIdChanged();
        /// <summary>
        /// There are no comments for Property BlogId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int BlogId
        {
            get
            {
                return this._BlogId;
            }
            set
            {
                this.OnBlogIdChanging(value);
                this.ReportPropertyChanging("BlogId");
                this._BlogId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("BlogId");
                this.OnBlogIdChanged();
            }
        }
        private int _BlogId;
        partial void OnBlogIdChanging(int value);
        partial void OnBlogIdChanged();
        /// <summary>
        /// There are no comments for Property Website in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Website
        {
            get
            {
                return this._Website;
            }
            set
            {
                this.OnWebsiteChanging(value);
                this.ReportPropertyChanging("Website");
                this._Website = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Website");
                this.OnWebsiteChanged();
            }
        }
        private string _Website;
        partial void OnWebsiteChanging(string value);
        partial void OnWebsiteChanged();
    }
    /// <summary>
    /// There are no comments for BlogsModel.tblBlogs_Posts in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="BlogsModel", Name="tblBlogs_Posts")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class tblBlogs_Posts : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tblBlogs_Posts object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="blogId">Initial value of BlogId.</param>
        /// <param name="content">Initial value of Content.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="published">Initial value of Published.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        /// <param name="modifiedBy">Initial value of ModifiedBy.</param>
        /// <param name="slug">Initial value of Slug.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="commentsEnabled">Initial value of CommentsEnabled.</param>
        /// <param name="viewCount">Initial value of ViewCount.</param>
        public static tblBlogs_Posts CreatetblBlogs_Posts(int id, int blogId, string content, global::System.DateTime createdDate, string createdBy, bool published, global::System.DateTime modifiedDate, string modifiedBy, string slug, string title, bool commentsEnabled, int viewCount)
        {
            tblBlogs_Posts tblBlogs_Posts = new tblBlogs_Posts();
            tblBlogs_Posts.Id = id;
            tblBlogs_Posts.BlogId = blogId;
            tblBlogs_Posts.Content = content;
            tblBlogs_Posts.CreatedDate = createdDate;
            tblBlogs_Posts.CreatedBy = createdBy;
            tblBlogs_Posts.Published = published;
            tblBlogs_Posts.ModifiedDate = modifiedDate;
            tblBlogs_Posts.ModifiedBy = modifiedBy;
            tblBlogs_Posts.Slug = slug;
            tblBlogs_Posts.Title = title;
            tblBlogs_Posts.CommentsEnabled = commentsEnabled;
            tblBlogs_Posts.ViewCount = viewCount;
            return tblBlogs_Posts;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property BlogId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int BlogId
        {
            get
            {
                return this._BlogId;
            }
            set
            {
                this.OnBlogIdChanging(value);
                this.ReportPropertyChanging("BlogId");
                this._BlogId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("BlogId");
                this.OnBlogIdChanged();
            }
        }
        private int _BlogId;
        partial void OnBlogIdChanging(int value);
        partial void OnBlogIdChanged();
        /// <summary>
        /// There are no comments for Property Content in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                this.OnContentChanging(value);
                this.ReportPropertyChanging("Content");
                this._Content = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Content");
                this.OnContentChanged();
            }
        }
        private string _Content;
        partial void OnContentChanging(string value);
        partial void OnContentChanged();
        /// <summary>
        /// There are no comments for Property ShortContent in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortContent
        {
            get
            {
                return this._ShortContent;
            }
            set
            {
                this.OnShortContentChanging(value);
                this.ReportPropertyChanging("ShortContent");
                this._ShortContent = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ShortContent");
                this.OnShortContentChanged();
            }
        }
        private string _ShortContent;
        partial void OnShortContentChanging(string value);
        partial void OnShortContentChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this.ReportPropertyChanging("CreatedDate");
                this._CreatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatedDate");
                this.OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this.ReportPropertyChanging("CreatedBy");
                this._CreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CreatedBy");
                this.OnCreatedByChanged();
            }
        }
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Published in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Published
        {
            get
            {
                return this._Published;
            }
            set
            {
                this.OnPublishedChanging(value);
                this.ReportPropertyChanging("Published");
                this._Published = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Published");
                this.OnPublishedChanged();
            }
        }
        private bool _Published;
        partial void OnPublishedChanging(bool value);
        partial void OnPublishedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this.ReportPropertyChanging("ModifiedBy");
                this._ModifiedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ModifiedBy");
                this.OnModifiedByChanged();
            }
        }
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Slug in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Slug
        {
            get
            {
                return this._Slug;
            }
            set
            {
                this.OnSlugChanging(value);
                this.ReportPropertyChanging("Slug");
                this._Slug = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Slug");
                this.OnSlugChanged();
            }
        }
        private string _Slug;
        partial void OnSlugChanging(string value);
        partial void OnSlugChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property CommentsEnabled in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool CommentsEnabled
        {
            get
            {
                return this._CommentsEnabled;
            }
            set
            {
                this.OnCommentsEnabledChanging(value);
                this.ReportPropertyChanging("CommentsEnabled");
                this._CommentsEnabled = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CommentsEnabled");
                this.OnCommentsEnabledChanged();
            }
        }
        private bool _CommentsEnabled;
        partial void OnCommentsEnabledChanging(bool value);
        partial void OnCommentsEnabledChanged();
        /// <summary>
        /// There are no comments for Property ViewCount in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ViewCount
        {
            get
            {
                return this._ViewCount;
            }
            set
            {
                this.OnViewCountChanging(value);
                this.ReportPropertyChanging("ViewCount");
                this._ViewCount = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ViewCount");
                this.OnViewCountChanged();
            }
        }
        private int _ViewCount;
        partial void OnViewCountChanging(int value);
        partial void OnViewCountChanged();
        /// <summary>
        /// There are no comments for Categories in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("BlogsModel", "tblBlogs_CategoriestblBlogs_Posts", "tblBlogs_Categories")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<tblBlogs_Categories> Categories
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<tblBlogs_Categories>("BlogsModel.tblBlogs_CategoriestblBlogs_Posts", "tblBlogs_Categories");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<tblBlogs_Categories>("BlogsModel.tblBlogs_CategoriestblBlogs_Posts", "tblBlogs_Categories", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for BlogsModel.tblBlogs_Friends in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="BlogsModel", Name="tblBlogs_Friends")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class tblBlogs_Friends : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tblBlogs_Friends object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="target">Initial value of Target.</param>
        public static tblBlogs_Friends CreatetblBlogs_Friends(int id, global::System.DateTime createdDate, string createdBy, string target)
        {
            tblBlogs_Friends tblBlogs_Friends = new tblBlogs_Friends();
            tblBlogs_Friends.Id = id;
            tblBlogs_Friends.CreatedDate = createdDate;
            tblBlogs_Friends.CreatedBy = createdBy;
            tblBlogs_Friends.Target = target;
            return tblBlogs_Friends;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this.ReportPropertyChanging("CreatedDate");
                this._CreatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatedDate");
                this.OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this.ReportPropertyChanging("CreatedBy");
                this._CreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CreatedBy");
                this.OnCreatedByChanged();
            }
        }
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Target in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Target
        {
            get
            {
                return this._Target;
            }
            set
            {
                this.OnTargetChanging(value);
                this.ReportPropertyChanging("Target");
                this._Target = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Target");
                this.OnTargetChanged();
            }
        }
        private string _Target;
        partial void OnTargetChanging(string value);
        partial void OnTargetChanged();
    }
}
