//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 5/31/2009 09:15
namespace MyLife.DataAccess.MoneyBox
{
    
    /// <summary>
    /// There are no comments for MoneyBoxEntities in the schema.
    /// </summary>
    public partial class MoneyBoxEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new MoneyBoxEntities object using the connection string found in the 'MoneyBoxEntities' section of the application configuration file.
        /// </summary>
        public MoneyBoxEntities() : 
                base("name=MoneyBoxEntities", "MoneyBoxEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MoneyBoxEntities object.
        /// </summary>
        public MoneyBoxEntities(string connectionString) : 
                base(connectionString, "MoneyBoxEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MoneyBoxEntities object.
        /// </summary>
        public MoneyBoxEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "MoneyBoxEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for tblMoneyBox_Categories in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<tblMoneyBox_Categories> tblMoneyBox_Categories
        {
            get
            {
                if ((this._tblMoneyBox_Categories == null))
                {
                    this._tblMoneyBox_Categories = base.CreateQuery<tblMoneyBox_Categories>("[tblMoneyBox_Categories]");
                }
                return this._tblMoneyBox_Categories;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tblMoneyBox_Categories> _tblMoneyBox_Categories;
        /// <summary>
        /// There are no comments for tblMoneyBox_Records in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<tblMoneyBox_Records> tblMoneyBox_Records
        {
            get
            {
                if ((this._tblMoneyBox_Records == null))
                {
                    this._tblMoneyBox_Records = base.CreateQuery<tblMoneyBox_Records>("[tblMoneyBox_Records]");
                }
                return this._tblMoneyBox_Records;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tblMoneyBox_Records> _tblMoneyBox_Records;
        /// <summary>
        /// There are no comments for tblMoneyBox_Categories in the schema.
        /// </summary>
        public void AddTotblMoneyBox_Categories(tblMoneyBox_Categories tblMoneyBox_Categories)
        {
            base.AddObject("tblMoneyBox_Categories", tblMoneyBox_Categories);
        }
        /// <summary>
        /// There are no comments for tblMoneyBox_Records in the schema.
        /// </summary>
        public void AddTotblMoneyBox_Records(tblMoneyBox_Records tblMoneyBox_Records)
        {
            base.AddObject("tblMoneyBox_Records", tblMoneyBox_Records);
        }
    }
    /// <summary>
    /// There are no comments for MyLifeModel.tblMoneyBox_Categories in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MyLifeModel", Name="tblMoneyBox_Categories")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class tblMoneyBox_Categories : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tblMoneyBox_Categories object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        /// <param name="modifiedBy">Initial value of ModifiedBy.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="colorHex">Initial value of ColorHex.</param>
        public static tblMoneyBox_Categories CreatetblMoneyBox_Categories(int id, global::System.DateTime createdDate, string createdBy, global::System.DateTime modifiedDate, string modifiedBy, string name, string colorHex)
        {
            tblMoneyBox_Categories tblMoneyBox_Categories = new tblMoneyBox_Categories();
            tblMoneyBox_Categories.Id = id;
            tblMoneyBox_Categories.CreatedDate = createdDate;
            tblMoneyBox_Categories.CreatedBy = createdBy;
            tblMoneyBox_Categories.ModifiedDate = modifiedDate;
            tblMoneyBox_Categories.ModifiedBy = modifiedBy;
            tblMoneyBox_Categories.Name = name;
            tblMoneyBox_Categories.ColorHex = colorHex;
            return tblMoneyBox_Categories;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this.ReportPropertyChanging("CreatedDate");
                this._CreatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatedDate");
                this.OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this.ReportPropertyChanging("CreatedBy");
                this._CreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CreatedBy");
                this.OnCreatedByChanged();
            }
        }
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this.ReportPropertyChanging("ModifiedBy");
                this._ModifiedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ModifiedBy");
                this.OnModifiedByChanged();
            }
        }
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property ColorHex in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorHex
        {
            get
            {
                return this._ColorHex;
            }
            set
            {
                this.OnColorHexChanging(value);
                this.ReportPropertyChanging("ColorHex");
                this._ColorHex = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ColorHex");
                this.OnColorHexChanged();
            }
        }
        private string _ColorHex;
        partial void OnColorHexChanging(string value);
        partial void OnColorHexChanged();
    }
    /// <summary>
    /// There are no comments for MyLifeModel.tblMoneyBox_Records in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MyLifeModel", Name="tblMoneyBox_Records")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class tblMoneyBox_Records : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tblMoneyBox_Records object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="modifiedDate">Initial value of ModifiedDate.</param>
        /// <param name="modifiedBy">Initial value of ModifiedBy.</param>
        /// <param name="categoryId">Initial value of CategoryId.</param>
        /// <param name="categoryName">Initial value of CategoryName.</param>
        /// <param name="encryptedAmount">Initial value of EncryptedAmount.</param>
        /// <param name="date">Initial value of Date.</param>
        public static tblMoneyBox_Records CreatetblMoneyBox_Records(int id, global::System.DateTime createdDate, string createdBy, global::System.DateTime modifiedDate, string modifiedBy, int categoryId, string categoryName, string encryptedAmount, global::System.DateTime date)
        {
            tblMoneyBox_Records tblMoneyBox_Records = new tblMoneyBox_Records();
            tblMoneyBox_Records.Id = id;
            tblMoneyBox_Records.CreatedDate = createdDate;
            tblMoneyBox_Records.CreatedBy = createdBy;
            tblMoneyBox_Records.ModifiedDate = modifiedDate;
            tblMoneyBox_Records.ModifiedBy = modifiedBy;
            tblMoneyBox_Records.CategoryId = categoryId;
            tblMoneyBox_Records.CategoryName = categoryName;
            tblMoneyBox_Records.EncryptedAmount = encryptedAmount;
            tblMoneyBox_Records.Date = date;
            return tblMoneyBox_Records;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this.ReportPropertyChanging("CreatedDate");
                this._CreatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatedDate");
                this.OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this.ReportPropertyChanging("CreatedBy");
                this._CreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CreatedBy");
                this.OnCreatedByChanged();
            }
        }
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this.ReportPropertyChanging("ModifiedDate");
                this._ModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ModifiedDate");
                this.OnModifiedDateChanged();
            }
        }
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this.ReportPropertyChanging("ModifiedBy");
                this._ModifiedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ModifiedBy");
                this.OnModifiedByChanged();
            }
        }
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property CategoryId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId
        {
            get
            {
                return this._CategoryId;
            }
            set
            {
                this.OnCategoryIdChanging(value);
                this.ReportPropertyChanging("CategoryId");
                this._CategoryId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CategoryId");
                this.OnCategoryIdChanged();
            }
        }
        private int _CategoryId;
        partial void OnCategoryIdChanging(int value);
        partial void OnCategoryIdChanged();
        /// <summary>
        /// There are no comments for Property CategoryName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName
        {
            get
            {
                return this._CategoryName;
            }
            set
            {
                this.OnCategoryNameChanging(value);
                this.ReportPropertyChanging("CategoryName");
                this._CategoryName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CategoryName");
                this.OnCategoryNameChanged();
            }
        }
        private string _CategoryName;
        partial void OnCategoryNameChanging(string value);
        partial void OnCategoryNameChanged();
        /// <summary>
        /// There are no comments for Property EncryptedAmount in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string EncryptedAmount
        {
            get
            {
                return this._EncryptedAmount;
            }
            set
            {
                this.OnEncryptedAmountChanging(value);
                this.ReportPropertyChanging("EncryptedAmount");
                this._EncryptedAmount = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("EncryptedAmount");
                this.OnEncryptedAmountChanged();
            }
        }
        private string _EncryptedAmount;
        partial void OnEncryptedAmountChanging(string value);
        partial void OnEncryptedAmountChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this.ReportPropertyChanging("Date");
                this._Date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Date");
                this.OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
    }
}
